lint:
  rules:
    no_default: true
    add:
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - REPEATED_FIELD_NAMES_PLURALIZED
      - IMPORTS_SORTED
      - ORDER
